# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cheung x Surya
email: cheungsurya@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Wow a celebration!
baseurl:  # the subpath of your site, e.g. /blog
url: "https://jsurya.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: chulapa-jekyll
plugins:
- jekyll-remote-theme
- jekyll-include-cache
remote_theme: dieghernan/chulapa

googlefonts:
 - url: "https://fonts.googleapis.com/css2?family=Euphoria+Script&family=PT+Mono&display=swap"
 

# B. Navigation
navbar:
  style :  fab

  brand:
    title :  Cheung x Surya
    url: /
    img: 
  nav:
  - title: Home #Label
    url: /  #url
  - title: Our Story #Label
    url: /#our-story  #url
  - title: Details #Label
    url: /#details  #url
   
footer:
  links:
    - label: "Email"
      icon: "fa fa-envelope"
      url:  "cheungsurya@gmail.com"
      color: 
  nav:
  - title: Home #Label
    url: /  #url 

# Theme and colors
chulapa-skin:
  skin         :  lux
  autothemer  : true
  vars:
    chulapa-bg-landingpage-color: "#e8e8e8"
    background-color: "#e8e8e8"
    headings-font-family: "PT Mono"
    font-family-base: "PT Mono"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
